# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
import numpy as np
a = np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [17]:
x = np.arange(10).reshape(2,5)
y = np.ones(10).reshape(2,5)
z = np.vstack((x,y))
print(z)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [22]:
u =np.hstack((x,y))
print(u)

[[0. 1. 2. 3. 4. 1. 1. 1. 1. 1.]
 [5. 6. 7. 8. 9. 1. 1. 1. 1. 1.]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [24]:
x.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [30]:
a1 = np.array([0,1,2,3,4,5,6,7,8,9.10,11,12,13,14], ndmin =6)
print(a1)
a = a1.flatten()
print(a)

[[[[[[ 0.   1.   2.   3.   4.   5.   6.   7.   8.   9.1 11.  12.
      13.  14. ]]]]]]
[ 0.   1.   2.   3.   4.   5.   6.   7.   8.   9.1 11.  12.  13.  14. ]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [35]:
a2 = np.arange(15)
a2 = np.reshape(a2,(5,3))
print(a2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [51]:
s = np.arange(25,50).reshape(5,5)
print(np.square(s))


[[ 625  676  729  784  841]
 [ 900  961 1024 1089 1156]
 [1225 1296 1369 1444 1521]
 [1600 1681 1764 1849 1936]
 [2025 2116 2209 2304 2401]]


## Question:8

### Create 5x6 an array and find the mean?

In [56]:
n1 = np.arange(20,50).reshape(5,6)
print("Mean of this is", np.mean(n1))

Mean of this is 34.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [58]:
print("standard deviation is ", np.std(n1))

standard deviation is  8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [59]:
print("median of the array is", np.median(n1))

median of the array is 34.5


## Question:11

### Find the transpose of the previous array in Q8?

In [61]:
print(" Transpose of the array is", np.transpose(n1))

 Transpose of the array is [[20 26 32 38 44]
 [21 27 33 39 45]
 [22 28 34 40 46]
 [23 29 35 41 47]
 [24 30 36 42 48]
 [25 31 37 43 49]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [68]:
x1 = np.arange(24,40).reshape(4,4)
diag = np.diagonal(x1)
print(sum(diag))

126


## Question:13

### Find the determinant of the previous array in Q12?

In [70]:
print("the determinent of the array is",np.linalg.det(x1))

the determinent of the array is 1.1688699944079557e-28


## Question:14

### Find the 5th and 95th percentile of an array?

In [77]:
arr = np.array([33,44,55,66,77,88,99])
r = np.percentile(arr,5)
t = np.percentile(arr,95)
print("the 5th percentile is ", r)
print("the 95th percentile is", t)


the 5th percentile is  36.3
the 95th percentile is 95.69999999999999


## Question:15

### How to find if a given array has any null values?

In [83]:
arr1 = np.array([11,0,33,0,55,66,0,0,9,54,32])
print(np.where(arr1 == 0))


(array([1, 3, 6, 7], dtype=int32),)
